// <auto-generated />
using System;
using ComputerInventoryAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerInventoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515083526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerInventoryAPI.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)")
                        .HasColumnName("Code");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "RTX4080   ",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "High-end Gaming GPU",
                            Name = "RTX 4080"
                        },
                        new
                        {
                            Code = "I9-14900K ",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "Flagship Desktop Processor",
                            Name = "Core i9"
                        },
                        new
                        {
                            Code = "VENGE-16GB",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 3,
                            Description = "High-speed DDR5 RAM",
                            Name = "Vengeance 16GB"
                        });
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "NV",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "INT",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "COR",
                            FoundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair"
                        });
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Pro",
                            Stock = 10,
                            Warranty = 24,
                            Weight = 4.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 15, 10, 35, 25, 887, DateTimeKind.Local).AddTicks(2630),
                            Name = "Workstation",
                            Stock = 2,
                            Warranty = 48,
                            Weight = 15f
                        });
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PcId = 1,
                            ComponentCode = "RTX4080   ",
                            Amount = 1
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "VENGE-16GB",
                            Amount = 2
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "VENGE-16GB",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.Component", b =>
                {
                    b.HasOne("ComputerInventoryAPI.Models.ComponentManufacturer", "Manufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerInventoryAPI.Models.ComponentType", "Type")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.PcComponent", b =>
                {
                    b.HasOne("ComputerInventoryAPI.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerInventoryAPI.Models.PC", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ComputerInventoryAPI.Models.PC", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
