services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Str0ng!Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Str0ng!Passw0rd", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: lpiwnik/computer-inventory-api:latest
    container_name: pc-inventory-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # WAŻNE: ASPNETCORE_ENVIRONMENT=Development jest wymagane do działania Swaggera.
      # W przypadku braku tego ustawienia (tryb Production), interfejs Swagger UI nie będzie dostępny.
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ComputerInventoryDB;User Id=sa;Password=Str0ng!Passw0rd;TrustServerCertificate=True
    ports:
      - "5229:8080"
